Medi_Assist/accounts/urls.py
from django.urls import path
from .views import *
from appointment.views import *

app_name = "accounts"

urlpatterns = [
    path('patient/register', RegisterPatientView.as_view(), name='patient-register'),
    path('patient/profile/update/', EditPatientProfileView.as_view(), name='patient-profile-update'),
    path('doctor/register', RegisterDoctorView.as_view(), name='doctor-register'),

    path('doctor/profile/update/', EditDoctorProfileView.as_view(), name='doctor-profile-update'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

Medi_Assist/appointment/urls.py
"""
doctor_appointment_system URL Configuration

"""

from django.urls import path
from appointment.views import *
from django.conf import settings
from django.conf.urls.static import static


app_name = 'appointment'

urlpatterns = [

    path('', HomePageView.as_view(), name='home'),
    #path('service', ServiceView.as_view(), name='service'),
    path('doctor/appointment/create', AppointmentCreateView.as_view(), name='doctor-appointment-create'),
    path('doctor/appointment/', AppointmentListView.as_view(), name='doctor-appointment'),
    path('<pk>/delete/', AppointmentDeleteView.as_view(), name='delete-appointment'),
    path('<pk>/patient/delete', PatientDeleteView.as_view(), name='delete-patient'),
    path('patient-take-appointment/<pk>', TakeAppointmentView.as_view(), name='take-appointment'),
    path('search/', SearchView.as_view(), name='search'),
   # path('ambulance-search/', SearchView.as_view(), name='ambulance-search'),
    path('ambulance/', AmbulanceView.as_view(), name='ambulance'),
    path('ambulance/search/', AmbulanceSearchView.as_view(), name='ambulance-search'),
    path('patient/', PatientListView.as_view(), name='patient-list'),
    path('lab-test/', LabTestView.as_view(), name='lab-test'),
    #path('patients/<int:appointment_id>', PatientPerAppointmentView.as_view(), name='patient-list'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Medi_Assist/doctor_appointment_system/urls.py
"""
doctor_appointment_system URL Configuration

"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('appointment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Medi_Assist/appointment/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from accounts.models import User

department = (
    ('Dentistry', "Dentistry"),
    ('Cardiology', "Cardiology"),
    ('ENT Specialists', "ENT Specialists"),
    ('Astrology', 'Astrology'),
    ('Neuroanatomy', 'Neuroanatomy'),
    ('Blood Screening', 'Blood Screening'),
    ('Eye Care', 'Eye Care'),
    ('Physical Therapy', 'Physical Therapy'),
)


class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank=True)
    location = models.CharField(max_length=100)
    start_time = models.CharField(max_length=10)
    end_time = models.CharField(max_length=10)
    qualification_name = models.CharField(max_length=100)
    institute_name = models.CharField(max_length=100)
    hospital_name = models.CharField(max_length=100)
    department = models.CharField(choices=department, max_length=100)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.full_name

    # def get_absolute_url(self):
    # return reverse('appointment:delete-appointment', kwargs={'pk': self.pk})


class TakeAppointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    m_phone_number = models.CharField(max_length=120)
    message = models.TextField()
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.full_name


class Ambulance(models.Model):
    title = models.CharField(max_length=120)
    location = models.CharField(max_length=100)
    image = models.ImageField(upload_to='media')
    phone_number = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class LabTest(models.Model):
    name = models.CharField(max_length=50)
    fee = models.IntegerField()
    image = models.ImageField(upload_to='media')

    def __str__(self):
        return self.name

Medi_Assist/appointment/forms.py
from django import forms
from .models import Appointment, TakeAppointment


class CreateAppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateAppointmentForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].label = "Full Name"

        self.fields['department'].label = "Department"
        self.fields['start_time'].label = "Start Time"
        self.fields['hospital_name'].label = "Hospital Name"
        self.fields['qualification_name'].label = "Qualification"
        self.fields['institute_name'].label = "Institute"

        self.fields['full_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Full Name',
            }
        )

        self.fields['department'].widget.attrs.update(
            {
                'placeholder': 'Select Your Service',
            }
        )

        self.fields['start_time'].widget.attrs.update(
            {
                'placeholder': 'Ex : 9 AM',
            }
        )
        self.fields['end_time'].widget.attrs.update(
            {
                'placeholder': 'Ex: 5 PM',
            }
        )
        self.fields['location'].widget.attrs.update(
            {
                'placeholder': 'Ex : Uttara, Dhaka',
            }
        )

        self.fields['hospital_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Hospital Name',
            }
        )

        self.fields['qualification_name'].widget.attrs.update(
            {
                'placeholder': 'Ex : MBBS, BDS',
            }
        )

        self.fields['institute_name'].widget.attrs.update(
            {
                'placeholder': 'Ex : DMC',
            }
        )

    class Meta:
        model = Appointment
        fields = ['full_name', 'image', 'department', 'start_time', 'end_time', 'location',
                  'hospital_name', 'qualification_name', 'institute_name']

    def is_valid(self):
        valid = super(CreateAppointmentForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        appointment = super(CreateAppointmentForm, self).save(commit=False)
        if commit:
            appointment.save()
        return appointment


class TakeAppointmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TakeAppointmentForm, self).__init__(*args, **kwargs)
        self.fields['appointment'].label = "Choose Your Doctor"
        self.fields['full_name'].label = "Full Name"
        self.fields['m_phone_number'].label = "Phone Number"
        self.fields['message'].label = "Message"

        self.fields['appointment'].widget.attrs.update(
            {
                'placeholder': 'Choose Your Doctor',
            }
        )

        self.fields['full_name'].widget.attrs.update(
            {
                'placeholder': 'Write Your Name',
            }
        )

        self.fields['m_phone_number'].widget.attrs.update(
            {
                'placeholder': 'Enter Phone Number',
            }
        )
        self.fields['message'].widget.attrs.update(
            {
                'placeholder': 'Write a short message',
            }
        )

    class Meta:
        model = TakeAppointment
        fields = ['appointment', 'full_name', 'm_phone_number', 'message']

    def is_valid(self):
        valid = super(TakeAppointmentForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        appointment = super(TakeAppointmentForm, self).save(commit=False)
        if commit:
            appointment.save()
        return appointment

Medi_Assist/appointment/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from accounts.models import User
from .decorators import user_is_patient, user_is_doctor
from django.views.generic import TemplateView, UpdateView, CreateView, ListView, DetailView, DeleteView
from django.views.generic.edit import DeleteView, UpdateView
from accounts.forms import PatientProfileUpdateForm, DoctorProfileUpdateForm
from .forms import CreateAppointmentForm, TakeAppointmentForm
from .models import *

"""
For Patient Profile
    
"""


class EditPatientProfileView(UpdateView):
    model = User
    form_class = PatientProfileUpdateForm
    context_object_name = 'patient'
    template_name = 'accounts/patient/edit-profile.html'
    success_url = reverse_lazy('accounts:patient-profile-update')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_patient)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            raise Http404("User doesn't exists")
        # context = self.get_context_data(object=self.object)
        return self.render_to_response(self.get_context_data())

    def get_object(self, queryset=None):
        obj = self.request.user
        print(obj)
        if obj is None:
            raise Http404("Patient doesn't exists")
        return obj


class TakeAppointmentView(CreateView):
    template_name = 'appointment/take_appointment.html'
    form_class = TakeAppointmentForm
    extra_context = {
        'title': 'Take Appointment'
    }
    success_url = reverse_lazy('appointment:home')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('accounts:login')
        if self.request.user.is_authenticated and self.request.user.role != 'patient':
            return reverse_lazy('accounts:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TakeAppointmentView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


"""
   For Doctor Profile
"""


class EditDoctorProfileView(UpdateView):
    model = User
    form_class = DoctorProfileUpdateForm
    context_object_name = 'doctor'
    template_name = 'accounts/doctor/edit-profile.html'
    success_url = reverse_lazy('accounts:doctor-profile-update')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_doctor)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            raise Http404("User doesn't exists")
        # context = self.get_context_data(object=self.object)
        return self.render_to_response(self.get_context_data())

    def get_object(self, queryset=None):
        obj = self.request.user
        print(obj)
        if obj is None:
            raise Http404("Patient doesn't exists")
        return obj


class AppointmentCreateView(CreateView):
    template_name = 'appointment/appointment_create.html'
    form_class = CreateAppointmentForm
    extra_context = {
        'title': 'Post New Appointment'
    }
    success_url = reverse_lazy('appointment:doctor-appointment')

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('accounts:login')
        if self.request.user.is_authenticated and self.request.user.role != 'doctor':
            return reverse_lazy('accounts:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AppointmentCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class AppointmentListView(ListView):
    model = Appointment
    template_name = 'appointment/appointment.html'
    context_object_name = 'appointment'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_doctor)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user_id=self.request.user.id).order_by('-id')


class PatientListView(ListView):
    model = TakeAppointment
    context_object_name = 'patients'
    template_name = "appointment/patient_list.html"

    def get_queryset(self):
        return self.model.objects.filter(appointment__user_id=self.request.user.id).order_by('-id')


class PatientDeleteView(DeleteView):
    model = TakeAppointment
    success_url = reverse_lazy('appointment:patient-list')


class AppointmentDeleteView(DeleteView):
    """
       For Delete any Appointment created by Doctor
    """
    model = Appointment
    success_url = reverse_lazy('appointment:doctor-appointment')


"""
   For both Profile
   
"""


class HomePageView(ListView):
    paginate_by = 9
    model = Appointment
    context_object_name = 'home'
    template_name = "home.html"

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')


class AmbulanceView(ListView):
    paginate_by = 9
    model = Ambulance
    context_object_name = 'ambulance'
    template_name = "ambulance/ambulance.html"

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')


class AmbulanceSearchView(ListView):

    model = Ambulance
    template_name = 'ambulance/search_ambulance.html'
    context_object_name = 'search'

    def get_queryset(self):
        return self.model.objects.filter(location__icontains=self.request.GET['location'])


class LabTestView(ListView):
    model = LabTest
    context_object_name = 'lab_test'
    template_name = "ambulance/lab_test_list.html"

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')


class SearchView(ListView):
    paginate_by = 6
    model = Appointment
    template_name = 'appointment/search.html'
    context_object_name = 'appointment'

    def get_queryset(self):
        return self.model.objects.filter(location__icontains=self.request.GET['location'],
                                         department__contains=self.request.GET['department'])

Medi_Assist/templates/appointment/appointment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Appointment List{% endblock %}



{% block content %}

    <section class="dentist-area section-padding-40-0">

    <div class="container">


      <div class="row">

        <!-- Section Heading -->
        <div class="col-12">
          <div class="section-heading text-center">


            <h3>{{ request.user.first_name }}'s Appointment/s</h3>
            <div class="line"></div>
          </div>
        </div>
      </div>

      <div class="row">
          {% for apt in appointment %}
        <!-- Single Dentist Area -->
        <div class="col-12 col-sm-6 col-md-4">

          <div class="single-dentist-area mb-100">
            <img  style="height: 400px; width: 450px" src="{{ apt.image.url }}" alt="">
            <!-- Dentist Content -->
            <div class="dentist-content">
              <!-- Social Info -->
              <div class="dentist-social-info">

              </div>
              <!-- Dentist Info -->
              <div class="dentist-info bg-gradient-overlay">
                <h5>{{ apt.full_name }}</h5>
                <p>{{ apt.department }} Expert</p>
                  <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                  <p>Available {{ apt.start_time }} to {{ apt.end_time }} in {{ apt.hospital_name }}</p>
                  <p> AT {{ apt.location }}
                      <i class="fa fa-trash-o" style="color: red" aria-hidden="true"></i>
                      <a href="{% url 'appointment:delete-appointment' apt.id %}">Delete Appointment</a>
                  </p>

              </div>
            </div>
          </div>
        </div>
      {% endfor %}

      </div>
    </div>
  </section>

{% endblock %}

Medi_Assist/templates/appointment/appointment_confirm_delete.html
{% extends 'base.html' %}
{% load  static %}

{% block title %}Appointment Delete{% endblock %}

{% block content %}

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-lg-5 mb-5 mb-lg-0">
                <center>
                    <h4 class="highlight">Are you sure you want to delete {{ object.full_name }}'s Appointment?</h4>

                </center>
                <form method="post" enctype="multipart/form-data">{% csrf_token %}


                    <img style="height: 400px; width: 450px" src="{{ object.image.url  }}" alt="">
                    </br>
                    </br>
                    <center><input class="btn btn-danger" type="submit" value="Delete">
                    </center>


                </form>
                </br>

            </div>
        </div>
    </div>


{% endblock %}

Medi_Assist/templates/appointment/appointment_create.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Appointment Create {% endblock %}

{% block content %}

    <section class="dentist-area section-padding-40-0">
<div class="container">

<div class="row justify-content-center">

                <div class="col-lg-5 mb-5 mb-lg-0">
                    <center> <h3>Create  Appointment</h3></center>

                    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

                        {{ form|bootstrap }}

                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Create" class="btn btn-primary btn-md text-white">
                            </div>
                        </div>


                    </form>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

Medi_Assist/templates/appointment/patient_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Patient List{% endblock %}

{% block content %}
    <section class="dentist-area section-padding-50-0">

        <div class="container" style="align-items: center; justify-content: center;display: flex;">
            <div class="col-12 col-sm-6 col-md-4">

                <h3 style="align-items: center;justify-content: center;display: flex"> {{ request.user.first_name }} has {{ patients.count }}
                    Patient/s</h3>

                </br >
                </br >
            </div>

        </div>

    </section>


    <section class="dentist-area section-padding-30-0">

        <div class="container">

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Phone Number</th>
                    <th scope="col">Message</th>
                    <th scope="col">Date</th>
                    <th scope="col">Actions</th>

                </tr>
                </thead>
                <tbody>

                {% for patient in patients %}
                    <tr>

                        <td>{{ patient.full_name }}</td>
                        <td> {{ patient.m_phone_number }}</td>
                        <td> {{ patient.message }}</td>
                        <td> {{ patient.date }}</td>
                        <td>

                            <a href="{% url 'appointment:delete-patient' patient.id %}">
                                <span class="glyphicon glyphicon-trash"></span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </section>

{% endblock %}

Medi_Assist/templates/appointment/search.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<section class="dentist-area section-padding-40-0">
 <div class="breadcumb-area bg-img bg-gradient-overlay"  style="background-image: url('{% static 'img/bg-img/13.jpg' %}');">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">

             <form id="job-main-form" method="get" action="" class="search-doctor-form">
                    <div class="row mb-5">


                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <input type="text" id="location" name="location"
                                   class="form-control form-control-lg" placeholder="Any Location ?  Ex : Uttara, Dhaka">
                        </div>

                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <select id="department" name="department" class="form-control">
                                 <option style="display: none;" >Select Your Service</option>
                                <option>Cardiology</option>
                                <option>Dentistry</option>
                                <option>ENT Specialists</option>
                                <option>Astrology</option>
                                <option>Neuroanatomy</option>
                                <option>Blood Screening</option>
                                <option>Eye Care</option>
                                <option>Physical Therapy</option>
                            </select>
                        </div>


                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <button type="submit" class="btn btn-primary btn-lg btn-block text-black btn-search"><span
                                    class="icon-search icon mr-2"></span>Search Doctor
                            </button>
                        </div>
                    </div>
                </form>


        </div>
      </div>
    </div>
  </div>


</section>



    <section class="dentist-area section-padding-50-0">


        <div class="container">

            <div class="row">

                <div class="col-12">
                    <div class="section-heading text-center">


                        <h3>We have found {{ appointment.count }} doctor/s. </h3>
                        <div class="line"></div>
                    </div>
                </div>
            </div>

            <div class="row">


                {% for apt in appointment %}
                    <!-- Single Dentist Area -->
                    <div class="col-12 col-sm-6 col-md-4">
                        <div class="single-dentist-area mb-100">
                            <img style="height: 400px; width: 450px" src="{{ apt.image.url }}" alt="">
                            <!-- Dentist Content -->
                            <div class="dentist-content">
                                <!-- Social Info -->
                                <div class="dentist-social-info">

                                </div>
                                <!-- Dentist Info -->
                                <div class="dentist-info bg-gradient-overlay">
                                    {% if request.user.is_authenticated and request.user.role == 'patient' %}

                                        <h5>{{ apt.full_name }}</h5>
                                        <p>{{ apt.department }} Expert</p>
                                        <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                                        <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                                            in {{ apt.hospital_name }}</p>
                                        <p>
                                            AT {{ apt.location }} <i class="fa fa-th"></i>
                                            <a href="{% url 'appointment:take-appointment' apt.id %}"> Take
                                                Appointment</a>

                                        </p>
                                    {% elif request.user.is_authenticated and request.user.role == 'doctor' %}

                                        <h5>{{ apt.full_name }}</h5>
                                        <p>{{ apt.department }} Expert</p>
                                        <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                                        <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                                            in {{ apt.hospital_name }}</p>
                                        <p>AT {{ apt.location }}


                                        </p>

                                    {% else %}

                                        <h5>{{ apt.full_name }}</h5>
                                        <p>{{ apt.department }} Expert</p>
                                        <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                                        <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                                            in {{ apt.hospital_name }}</p>
                                        <p>AT {{ apt.location }}



                                        </p>

                                    {% endif %}

                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}


                <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
                </div>


            </div>

        </div>
    </section>


{% endblock %}

Medi_Assist/templates/appointment/take_appointment.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Take Appointment {% endblock %}



{% block content %}
    <div class="container">

        <div class="row justify-content-center">

            <div class="col-lg-5 mb-5 mb-lg-0">
                <center><h3>Take Appointment </h3></center>

                <form action="" method="POST">{% csrf_token %}

                    {{ form|bootstrap }}

                    <div class="row form-group">
                        <div class="col-md-12">
                            <input onclick="myFunction()" type="submit" value="Submit"
                                   class="btn btn-primary btn-md text-white">
                        </div>
                    </div>
                </form>

                <script>
                    function myFunction() {
                        alert("Are you sure taking  this appointment?");
                    }

                </script>
            </div>

        </div>
    </div>

{% endblock %}

Medi_Assist/templates/appointment/takeappointment_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Appointment Delete{% endblock %}

{% block content %}

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-lg-5 mb-5 mb-lg-0">
                <center>
                    <h4 class="highlight">Are you sure you want to delete this patient?</h4>

                </center>


                <form method="post">{% csrf_token %}

                    <table class="table">
                        <thead>
                        <tr>

                            <th scope="col">Name</th>
                            <th scope="col">Phone Number</th>
                            <th scope="col">Message</th>
                            <th scope="col">Date</th>


                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                             <td> {{ object.full_name }}</td>
                            <td> {{ object.phone_number }}</td>
                            <td>{{ object.message }}</td>
                            <td>{{ object.date }}</td>
                        </tr>
                        </br>
                        </br>
                        </tbody>
                    </table>
                    <center><input class="btn btn-danger" type="submit" value="Delete">
                    </center>


                </form>


                </br>

            </div>
        </div>
    </div>


{% endblock %}