Medi_Assist/accounts/urls.py
from django.urls import path
from .views import *
from appointment.views import *

app_name = "accounts"

urlpatterns = [
    path('patient/register', RegisterPatientView.as_view(), name='patient-register'),
    path('patient/profile/update/', EditPatientProfileView.as_view(), name='patient-profile-update'),
    path('doctor/register', RegisterDoctorView.as_view(), name='doctor-register'),

    path('doctor/profile/update/', EditDoctorProfileView.as_view(), name='doctor-profile-update'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

Medi_Assist/appointment/urls.py
"""
doctor_appointment_system URL Configuration

"""

from django.urls import path
from appointment.views import *
from django.conf import settings
from django.conf.urls.static import static


app_name = 'appointment'

urlpatterns = [

    path('', HomePageView.as_view(), name='home'),
    #path('service', ServiceView.as_view(), name='service'),
    path('doctor/appointment/create', AppointmentCreateView.as_view(), name='doctor-appointment-create'),
    path('doctor/appointment/', AppointmentListView.as_view(), name='doctor-appointment'),
    path('<pk>/delete/', AppointmentDeleteView.as_view(), name='delete-appointment'),
    path('<pk>/patient/delete', PatientDeleteView.as_view(), name='delete-patient'),
    path('patient-take-appointment/<pk>', TakeAppointmentView.as_view(), name='take-appointment'),
    path('search/', SearchView.as_view(), name='search'),
   # path('ambulance-search/', SearchView.as_view(), name='ambulance-search'),
    path('ambulance/', AmbulanceView.as_view(), name='ambulance'),
    path('ambulance/search/', AmbulanceSearchView.as_view(), name='ambulance-search'),
    path('patient/', PatientListView.as_view(), name='patient-list'),
    path('lab-test/', LabTestView.as_view(), name='lab-test'),
    #path('patients/<int:appointment_id>', PatientPerAppointmentView.as_view(), name='patient-list'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Medi_Assist/doctor_appointment_system/urls.py
"""
doctor_appointment_system URL Configuration

"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('appointment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Medi_Assist/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="description" content="Dento - Dentist &amp; Medical HTML Template">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Title -->
  <title>Medi Assist {% block title %} {% endblock %}</title>

  <!-- Favicon -->
  <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">

  <!-- Core Stylesheet -->
  <link rel="stylesheet" href="{% static 'style.css' %}">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    {% block styles %} {% endblock %}

</head>

<body>
   {% include 'nav.html' %}

  <!-- ***** Header Area End ***** -->
      {% block content %}
  {% endblock  %}
  <!-- ***** Welcome Area Start ***** -->

  <!-- ***** Blog Area End ***** -->

  <!-- ***** Footer Area Start ***** -->
  <footer class="footer-area bg-img bg-gradient-overlay">
    <div class="container">
      <div class="row">
        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg-4">
          <div class="single-footer-widget">
            <a href="./index.html" class="d-block mb-4"><img src="{% static 'img/logo.png' %}" alt=""></a>

            <div class="footer-contact">
                 <p> We Believe Everyone Should Have Easy Access To Great Medical Care</p>
              <p> Dhaka, Bangladesh</p>
              <p> +88 01798128...</p>
              <p> info.mediassist@gmail.com</p>
            </div>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <!-- Widget Title -->
            <h5 class="widget-title">Opening Hours</h5>

            <!-- Opening Hours -->
            <ul class="opening-hours">
              <li><span>Mon-Wed</span> <span>8.00 AM-10.00 PM</span></li>
              <li><span>Thu-Fri</span> <span>8.00 AM-10.00 PM</span></li>
              <li><span>Sat</span> <span>8.00 AM-10.00 PM</span></li>
              <li><span>Sun</span> <span>8.00 AM-10.00 PM</span></li>
              <li><span>Holiday</span> <span>Closed</span></li>
            </ul>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <!-- Widget Title -->
            <h5 class="widget-title">Quick Link</h5>

            <!-- Quick Links Nav -->
            <nav>
              <ul class="quick-links">
                <li><a href="#">About</a></li>
                <li><a href="#">FAQs</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">Policy</a></li>
                <li><a href="#">News</a></li>
                <li><a href="#">Advisors</a></li>
                <li><a href="#">Careers</a></li>
                <li><a href="#">Dentist</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Legals</a></li>
              </ul>
            </nav>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg">
          <div class="single-footer-widget">
            <!-- Widget Title -->
            <h5 class="widget-title">Newsletter</h5>

            <p>We will send out weekly newest article and some great offers</p>
            <!-- Newsletter Form -->
            <div class="footer-newsletter-form">
              <form action="#" method="post">
                <input type="email" name="nl-email" value="" placeholder="Email Address">
                <button type="submit"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
              </form>
            </div>

            <!-- Social Info -->
            <div class="footer-social-info">
              <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Google Plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Linkedin"><i class="fa fa-linkedin"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Copywrite Area -->
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="copywrite-content">
            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://docmed.com" target="_blank">Docmed</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- ***** Footer Area End ***** -->

  <!-- ******* All JS ******* -->
  <!-- jQuery js -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Popper js -->
  <script src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap js -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- All js -->
  <script src="{% static 'js/dento.bundle.js' %}"></script>
  <!-- Active js -->
  <script src="{% static 'js/default-assets/active.js' %}"></script>


   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

   {% block javascripts %} {% endblock %}
</body>

</html>

Medi_Assist/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Home{% endblock %}


{% block content %}

    <!-- ***** Welcome Area Start ***** -->
  <section class="welcome-area">
    <!-- Welcome Slides -->
    <div class="welcome-slides owl-carousel">
      <!-- Single Welcome Slide -->
      <div class="welcome-welcome-slide bg-img bg-gradient-overlay jarallax"  style="background-image: url('{% static 'img/bg-img/1.jpg' %}');">
        <div class="container h-100">
          <div class="row h-100 align-items-center">
            <div class="col-12">
              <!-- Welcome Text -->
              <div class="welcome-text text-center">
                <h2 data-animation="fadeInUp" data-delay="100ms">We Believe Everyone Should Have Easy Access To Great Health Care</h2>


                <div class="welcome-btn-group">

                    <form id="job-main-form" method="get" action="{% url 'appointment:search' %}" class="search-doctor-form">
                    <div class="row mb-5">


                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <input type="text" id="location" name="location"
                                   class="form-control form-control-lg" placeholder="Any Location ?  Ex : Uttara, Dhaka">
                        </div>

                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">


                            <select id="department" name="department" class="form-control">
                                <option style="display: none;" >Select Your Service</option>
                                <option>Cardiology</option>
                                <option>Dentistry</option>
                                <option>ENT Specialists</option>
                                <option>Astrology</option>
                                <option>Neuroanatomy</option>
                                <option>Blood Screening</option>
                                <option>Eye Care</option>
                                <option>Physical Therapy</option>
                            </select>
                        </div>


                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <button type="submit" class="btn btn-primary btn-lg btn-block text-black btn-search"><span
                                    class="icon-search icon mr-2"></span>Search Doctor
                            </button>
                        </div>
                    </div>
                </form>




                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Single Welcome Slide -->

    </div>
  </section>



    <section class="dentist-area section-padding-35-0">

        <div class="container">



            <div class="row">

                <div class="col-12">
                    <div class="section-heading text-center">
                         </br>

                        <h3 class="lead">Available Doctors </h3>
                        <div class="line"></div>
                    </div>
                </div>
            </div>

            <div class="row">


                {% for apt in home %}
                    <!-- Single Dentist Area -->
                    <div class="col-12 col-sm-6 col-md-4">
                        <div class="single-dentist-area mb-100">
                            <img style="height: 400px; width: 450px" src="{{ apt.image.url }}" alt="">
                            <!-- Dentist Content -->
                            <div class="dentist-content">
                                <!-- Social Info -->
                                <div class="dentist-social-info">

                                </div>
                                <!-- Dentist Info -->
                                <div class="dentist-info bg-gradient-overlay">
                                    {% if request.user.is_authenticated and request.user.role == 'patient' %}
                                        <h5>{{ apt.full_name }}</h5>
                                        <p>{{ apt.department }} Expert</p>
                                        <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                                        <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                                            in {{ apt.hospital_name }}</p>
                                        <p>
                                            AT {{ apt.location }} <i class="fa fa-th"></i>
                                            <a href="{% url 'appointment:take-appointment' apt.id %}"> Take
                                                Appointment</a>

                                        </p>
                                    {% elif request.user.is_authenticated and request.user.role == 'doctor'   %}

                                        <h5>{{ apt.full_name }}</h5>
                                        <p>{{ apt.department }} Expert</p>
                                        <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                                        <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                                            in {{ apt.hospital_name }}</p>
                                        <p>AT {{ apt.location }}</p>

                                        {% else %}

                                         <h5>{{ apt.full_name }}</h5>
                                        <p>{{ apt.department }} Expert</p>
                                        <p>{{ apt.qualification_name }}, {{ apt.institute_name }}</p>
                                        <p>Available {{ apt.start_time }} to {{ apt.end_time }}
                                            in {{ apt.hospital_name }}</p>
                                        <p>
                                            AT {{ apt.location }} </p>


                                    {% endif %}

                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}


                <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
                </div>


            </div>

        </div>
    </section>

{% endblock %}

Medi_Assist/templates/nav.html
{% load static %}
<!-- Preloader -->
<!-- Preloader -->


<div id="preloader">
    <div class="preload-content">
        <div id="dento-load"></div>
    </div>
</div>

<!-- ***** Header Area Start ***** -->
<header class="header-area">
    <!-- Top Header Area -->
    <div class="top-header-area">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <!-- Top Content -->
                <div class="col-6 col-md-9 col-lg-8">
                    <div class="top-header-content">
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Dhaka, Bangladesh"><i
                                class="fa fa-map-marker"></i> <span>Dhaka, Bangladesh</span></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="info.mediassist@gmail.com"><i
                                class="fa fa-envelope"></i> <span>info.mediassist@gmail.com</span></a>
                    </div>
                </div>
                <!-- Top Header Social Info -->
                <div class="col-6 col-md-3 col-lg-4">
                    <div class="top-header-social-info text-right">
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i
                                class="fa fa-facebook"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i
                                class="fa fa-twitter"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i
                                class="fa fa-google-plus"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Linkedin"><i
                                class="fa fa-linkedin"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i
                                class="fa fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Top Header End -->

    <!-- Main Header Start -->
    <div class="main-header-area">
        <div class="classy-nav-container breakpoint-off">
            <div class="container">
                <!-- Classy Menu -->
                <nav class="classy-navbar justify-content-between" id="dentoNav">

                    <!-- Logo -->
                    <a class="nav-brand" href="{% url 'appointment:home' %}"><img src="{% static 'img/logo.png' %}" alt="">
                    </a>

                    <!-- Navbar Toggler -->
                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <!-- Menu -->
                    <div class="classy-menu">

                        <!-- Close Button -->
                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <!-- Nav Start -->
                        <div class="classynav">


                            <ul id="nav">

                                <li><a href="{% url 'appointment:home' %}">Home</a></li>


                                 <li><a href="#">Services</a>
                                        <ul class="dropdown">
                                            <li><a href="{% url 'appointment:ambulance' %}"> AMBULANCE</a></li>
                                            <li><a href="{% url 'appointment:lab-test' %}"> LAB TEST</a></li>
                                        </ul>
                                    </li>


                                {% if request.user.is_authenticated and request.user.role == 'doctor' %}

                                    <li>
                                        <a href="">
                                            <span class="glyphicon glyphicon-user">
                                                    {{ request.user.first_name }}
                                            </span>
                                        </a>
                                        <ul class="dropdown">
                                            <li><a href="{% url 'accounts:doctor-profile-update'  %}"> EDIT PROFILE</a></li>
                                            <li><a href="{% url 'appointment:patient-list' %}"> PATIENTS</a></li>
                                            <li><a href="{% url 'appointment:doctor-appointment' %}">  APPOINTMENTS</a></li>
                                            <li><a href="{% url 'appointment:doctor-appointment-create' %}"> CREATE APPOINTMENT</a></li>
                                            <li><a href="{% url 'accounts:logout' %}"> LOGOUT</a></li>

                                        </ul>
                                    </li>


                             {% elif request.user.is_authenticated and request.user.role == 'patient' %}
                                    <li>
                                        <a href="">
                                            <span class="glyphicon glyphicon-user">
                                                    {{ request.user.first_name }}
                                            </span>
                                        </a>
                                        <ul class="dropdown">

                                            <li><a href="{% url 'accounts:patient-profile-update'  %}"> EDIT PROFILE</a></li>
                                            <li><a href="{% url 'accounts:logout' %}"> LOGOUT</a></li>

                                        </ul>
                                    </li>




                              {% else %}
                                    <li><a href="#">Register</a>
                                        <ul class="dropdown">
                                            <li><a href="{% url 'accounts:doctor-register' %}"> DOCTOR</a></li>
                                            <li><a href="{% url 'accounts:patient-register' %}"> PATIENT</a></li>
                                        </ul>
                                    </li>

                                    <li>
                                        <a href="{% url 'accounts:login' %}">
                                            <span class="glyphicon glyphicon-user"> login</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>

                        </div>
                        <!-- Nav End -->
                    </div>

                    <!-- Booking Now Button -->


                </nav>
            </div>
        </div>
    </div>
</header>