Medi_Assist/accounts/urls.py
from django.urls import path
from .views import *
from appointment.views import *

app_name = "accounts"

urlpatterns = [
    path('patient/register', RegisterPatientView.as_view(), name='patient-register'),
    path('patient/profile/update/', EditPatientProfileView.as_view(), name='patient-profile-update'),
    path('doctor/register', RegisterDoctorView.as_view(), name='doctor-register'),

    path('doctor/profile/update/', EditDoctorProfileView.as_view(), name='doctor-profile-update'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

Medi_Assist/appointment/urls.py
"""
doctor_appointment_system URL Configuration

"""

from django.urls import path
from appointment.views import *
from django.conf import settings
from django.conf.urls.static import static


app_name = 'appointment'

urlpatterns = [

    path('', HomePageView.as_view(), name='home'),
    #path('service', ServiceView.as_view(), name='service'),
    path('doctor/appointment/create', AppointmentCreateView.as_view(), name='doctor-appointment-create'),
    path('doctor/appointment/', AppointmentListView.as_view(), name='doctor-appointment'),
    path('<pk>/delete/', AppointmentDeleteView.as_view(), name='delete-appointment'),
    path('<pk>/patient/delete', PatientDeleteView.as_view(), name='delete-patient'),
    path('patient-take-appointment/<pk>', TakeAppointmentView.as_view(), name='take-appointment'),
    path('search/', SearchView.as_view(), name='search'),
   # path('ambulance-search/', SearchView.as_view(), name='ambulance-search'),
    path('ambulance/', AmbulanceView.as_view(), name='ambulance'),
    path('ambulance/search/', AmbulanceSearchView.as_view(), name='ambulance-search'),
    path('patient/', PatientListView.as_view(), name='patient-list'),
    path('lab-test/', LabTestView.as_view(), name='lab-test'),
    #path('patients/<int:appointment_id>', PatientPerAppointmentView.as_view(), name='patient-list'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Medi_Assist/doctor_appointment_system/urls.py
"""
doctor_appointment_system URL Configuration

"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('appointment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Medi_Assist/templates/ambulance/ambulance.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<section class="dentist-area section-padding-40-0">
<div class="breadcumb-area bg-img bg-gradient-overlay"  style="background-image: url('{% static 'img/bg-img/13.jpg' %}');">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">

             <form id="job-main-form" method="get" action="{% url 'appointment:ambulance-search' %}" class="search-doctor-form">
                    <div class="row mb-5">
                         <div class="col-12 col-sm-6 col-md-6 col-lg-2 mb-4 mb-lg-0">

                        </div>

                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <input type="text" id="location" name="location"
                                   class="form-control form-control-lg" placeholder="Any Location ?  Ex : Uttara, Dhaka">
                        </div>




                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <button type="submit" class="btn btn-primary btn-lg btn-block text-black btn-search"><span
                                    class="icon-search icon mr-2"></span>Search Ambulance
                            </button>
                        </div>
                    </div>
                </form>
        </div>
      </div>
    </div>

 </div>

</section>



    <section class="dentist-area section-padding-50-0">


        <div class="container">

            <div class="row">

                <div class="col-12">
                    <div class="section-heading text-center">


                        <h3> {{ ambulance.count }}  Ambulance Available </h3>
                        <div class="line"></div>
                    </div>
                </div>
            </div>

            <div class="row">


                {% for apt in ambulance %}
                    <!-- Single Dentist Area -->
                    <div class="col-12 col-sm-6 col-md-4">
                        <div class="single-dentist-area mb-100">
                            <img style="height: 300px; width: 350px" src="{{ apt.image.url }}" alt="">
                            <!-- Dentist Content -->
                            <div class="dentist-content">
                                <!-- Social Info -->
                                <div class="dentist-social-info">

                                </div>
                                <!-- Dentist Info -->
                                <div class="dentist-info bg-gradient-overlay">


                                        <h5>{{ apt.title }}</h5>
                                        <p>{{ apt.location }} </p>

                                        <p>Contact : {{ apt.phone_number }}</p>




                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}


                <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
                </div>


            </div>

        </div>
    </section>


{% endblock %}

Medi_Assist/templates/ambulance/lab_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Medi_Assist/templates/ambulance/lab_test_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Patient List{% endblock %}

{% block content %}




    <section class="dentist-area section-padding-30-0">

        <div class="container">

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Fee</th>
                    <th scope="col">Image</th>


                </tr>
                </thead>
                <tbody>

                {% for test in lab_test %}
                    <tr>

                        <td>{{ test.name }}</td>
                        <td> {{ test.fee }} TK</td>
                        <td>   <img style="height: 50px; width: 70px" src="{{ test.image.url }}" alt=""></td>


                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </section>
{% endblock %}

Medi_Assist/templates/ambulance/search_ambulance.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<section class="dentist-area section-padding-40-0">
<div class="breadcumb-area bg-img bg-gradient-overlay"  style="background-image: url('{% static 'img/bg-img/13.jpg' %}');">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12">

             <form id="job-main-form" method="get" action="" class="search-doctor-form">
                    <div class="row mb-5">
                         <div class="col-12 col-sm-6 col-md-6 col-lg-2 mb-4 mb-lg-0">

                        </div>

                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <input type="text" id="location" name="location"
                                   class="form-control form-control-lg" placeholder="Any Location ?  Ex : Uttara, Dhaka">
                        </div>




                        <div class="col-12 col-sm-6 col-md-6 col-lg-4 mb-4 mb-lg-0">
                            <button type="submit" class="btn btn-primary btn-lg btn-block text-black btn-search"><span
                                    class="icon-search icon mr-2"></span>Search Ambulance
                            </button>
                        </div>
                    </div>
                </form>
        </div>
      </div>
    </div>

 </div>

</section>



    <section class="dentist-area section-padding-50-0">


        <div class="container">

            <div class="row">

                <div class="col-12">
                    <div class="section-heading text-center">


                        <h3> We have found {{ search.count }}  Ambulance  </h3>
                        <div class="line"></div>
                    </div>
                </div>
            </div>

            <div class="row">


                {% for apt in search %}
                    <!-- Single Dentist Area -->
                    <div class="col-12 col-sm-6 col-md-4">
                        <div class="single-dentist-area mb-100">
                            <img style="height: 300px; width: 350px" src="{{ apt.image.url }}" alt="">
                            <!-- Dentist Content -->
                            <div class="dentist-content">
                                <!-- Social Info -->
                                <div class="dentist-social-info">

                                </div>
                                <!-- Dentist Info -->
                                <div class="dentist-info bg-gradient-overlay">


                                        <h5>{{ apt.title }}</h5>
                                        <p>{{ apt.location }} </p>

                                        <p>Contact : {{ apt.phone_number }}</p>




                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}





            </div>

        </div>
    </section>


{% endblock %}